# Generated by Django 3.2.11 on 2022-01-29 17:46

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file_import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_import', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл импорта',
                'verbose_name_plural': 'Файлы импорта',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('alphaMap', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Непрозрачность')),
                ('color', colorfield.fields.ColorField(default='#999999', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('metalness', models.FloatField(default=0.5, verbose_name='Метал')),
                ('roughness', models.FloatField(default=0.5, verbose_name='Шероховатость')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ЛДСП', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
            },
        ),
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('width', models.FloatField(default=0, verbose_name='Ширина')),
                ('height', models.FloatField(default=0, verbose_name='Вісота')),
                ('depth', models.FloatField(default=0, verbose_name='Глубина')),
                ('visible', models.BooleanField(default=False, verbose_name='Видимая')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default.jpg', max_length=100, verbose_name='Название')),
                ('mtexture', models.ImageField(default='default.jpg', height_field=512, upload_to='texture/', width_field=512)),
            ],
            options={
                'verbose_name': 'Текстуру',
                'verbose_name_plural': 'Текстуры',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('material', models.CharField(default='', max_length=100, verbose_name='Материал')),
                ('thickness', models.FloatField(default=0)),
                ('posx', models.FloatField(default=0)),
                ('posy', models.FloatField(default=0)),
                ('posz', models.FloatField(default=0)),
                ('rotx', models.FloatField(default=0)),
                ('roty', models.FloatField(default=0)),
                ('rotz', models.FloatField(default=0)),
                ('rotw', models.FloatField(default=0)),
                ('texture', models.IntegerField(default=0)),
                ('materialId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bazis.material')),
                ('mebel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bazis.mebel')),
            ],
            options={
                'verbose_name': 'Панель',
                'verbose_name_plural': 'Панели',
            },
        ),
        migrations.CreateModel(
            name='MaterialEqual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(default='', max_length=100, verbose_name='Материал')),
                ('materialId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bazis.material')),
                ('mebel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bazis.mebel')),
            ],
            options={
                'verbose_name': 'Материал панели',
                'verbose_name_plural': 'Материал панелей',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazis.texture'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazis.materialtype'),
        ),
        migrations.CreateModel(
            name='Contours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('pos1x', models.FloatField(default=0)),
                ('pos2x', models.FloatField(default=0)),
                ('pos1y', models.FloatField(default=0)),
                ('pos2y', models.FloatField(default=0)),
                ('centerx', models.FloatField(default=0)),
                ('centery', models.FloatField(default=0)),
                ('radius', models.FloatField(default=0)),
                ('start_angle', models.FloatField(default=0)),
                ('end_angle', models.FloatField(default=0)),
                ('arc_dir', models.BooleanField(default=False)),
                ('panel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bazis.panels')),
            ],
            options={
                'verbose_name': 'Контур',
                'verbose_name_plural': 'Контурі',
            },
        ),
    ]
