# Generated by Django 3.2.11 on 2022-01-22 17:26

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file_import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_import', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл импорта',
                'verbose_name_plural': 'Файлы импорта',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ЛДСП', max_length=50)),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default.jpg', max_length=50, verbose_name='Название')),
                ('mtexture', models.ImageField(default='default.jpg', upload_to='bazis/static/texture/')),
            ],
            options={
                'verbose_name': 'Текстуру',
                'verbose_name_plural': 'Текстуры',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('width', models.FloatField(default=0, verbose_name='Ширина')),
                ('height', models.FloatField(default=0, verbose_name='Вісота')),
                ('depth', models.FloatField(default=0, verbose_name='Глубина')),
                ('visible', models.BooleanField(default=False, verbose_name='Показівать')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('alphaMap', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Непрозрачность')),
                ('color', colorfield.fields.ColorField(default='#999999', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('metalness', models.FloatField(default=0.5, verbose_name='Метал')),
                ('roughness', models.FloatField(default=0.5, verbose_name='Шероховатость')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazis.texture')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazis.materialtype')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
