# Generated by Django 3.2.11 on 2022-01-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default.jpg', max_length=100, verbose_name='Название')),
                ('mtexture', models.ImageField(default='default.jpg', height_field=512, upload_to='texture/', width_field=512)),
            ],
            options={
                'verbose_name': 'Текстуру',
                'verbose_name_plural': 'Текстуры',
            },
        ),
    ]
