# Generated by Django 3.2.11 on 2022-01-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.ImageField(upload_to='texture/')),
            ],
        ),
    ]
