# Generated by Django 3.2.11 on 2022-01-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0002_texture'),
    ]

    operations = [
        migrations.AddField(
            model_name='texture',
            name='title',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='texture',
            name='texture',
            field=models.ImageField(default='default.jpg', upload_to='bazis/static/texture/'),
        ),
    ]
