# Generated by Django 3.2.11 on 2022-01-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0003_auto_20220121_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texture',
            old_name='texture',
            new_name='mtexture',
        ),
    ]
