# Generated by Django 3.2.11 on 2022-01-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0004_auto_20220129_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='pos',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
    ]
