# Generated by Django 3.2.11 on 2022-01-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0004_rename_texture_texture_mtexture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ЛДСП', max_length=50)),
            ],
        ),
    ]
