# Generated by Django 3.2.11 on 2022-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0005_panels_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='materialequal',
            name='materialName',
            field=models.CharField(default='', max_length=1000, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='texture',
            name='title',
            field=models.CharField(default='default.jpg', max_length=1000, verbose_name='Название'),
        ),
    ]
