# Generated by Django 3.2.11 on 2022-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0005_materialtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texture',
            options={'verbose_name': 'Текстура', 'verbose_name_plural': 'Текстуры'},
        ),
        migrations.AlterField(
            model_name='texture',
            name='title',
            field=models.CharField(default='default.jpg', max_length=50, verbose_name='Название'),
        ),
    ]
