# Generated by Django 3.2.11 on 2022-01-21 19:43

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0006_auto_20220121_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': 'Тип материала', 'verbose_name_plural': 'Типы материала'},
        ),
        migrations.AlterModelOptions(
            name='texture',
            options={'verbose_name': 'Текстуру', 'verbose_name_plural': 'Текстуры'},
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('alphaMap', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('color', colorfield.fields.ColorField(default='#999999', image_field=None, max_length=18, samples=None)),
                ('metalness', models.FloatField(default=0.5)),
                ('roughness', models.FloatField(default=0.5)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazis.texture')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazis.materialtype')),
            ],
        ),
    ]
