# Generated by Django 3.2.11 on 2022-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0006_auto_20220129_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panels',
            name='material',
            field=models.CharField(default='', max_length=1000, verbose_name='Материал Базиса'),
        ),
    ]
