# Generated by Django 3.2.11 on 2022-01-21 19:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0008_auto_20220121_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': 'Тип материала', 'verbose_name_plural': 'Типы материалов'},
        ),
        migrations.AlterField(
            model_name='material',
            name='alphaMap',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Непрозрачность'),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=colorfield.fields.ColorField(default='#999999', image_field=None, max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='material',
            name='metalness',
            field=models.FloatField(default=0.5, verbose_name='Метал'),
        ),
        migrations.AlterField(
            model_name='material',
            name='roughness',
            field=models.FloatField(default=0.5, verbose_name='Шероховатость'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
