# Generated by Django 3.2.11 on 2022-01-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazis', '0009_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='alphaMap',
        ),
        migrations.RemoveField(
            model_name='material',
            name='color',
        ),
    ]
